definitions:
    synchronize_marketing_list_item_for_mailchimp_member_activity:
        label:   'Synchronizes OroCRM Marketing List Item for MailChimp Member Activity'
        enabled: true
        entity:  OroCRM\Bundle\MailChimpBundle\Entity\MemberActivity
        actions_configuration:
            - @update_email_campaign_statistics: ~

    create_email_campaign_for_mailchimp_campaign:
        label:   Create Email Campaign for MailChimp Campaign
        enabled: true
        entity:  OroCRM\Bundle\MailChimpBundle\Entity\Campaign
        exclude_definitions: [create_email_campaign_for_mailchimp_campaign]
        actions_configuration:
            - @tree:
                actions:
                    # Prepare constants values
                    - @assign_constant_value:
                        attribute: $.statusSent
                        value: OroCRM\Bundle\MailChimpBundle\Entity\Campaign::STATUS_SENT
                    - @assign_constant_value:
                        attribute: $.scheduleManual
                        value: OroCRM\Bundle\CampaignBundle\Entity\EmailCampaign::SCHEDULE_MANUAL
                    - @assign_constant_value:
                        attribute: $.mailchimpTransport
                        value: OroCRM\Bundle\MailChimpBundle\Transport\MailChimpTransport::NAME
                    # Create OroCRM EmailCampaign
                    - @tree:
                        # If OroCRM EmailCampaign not exists and
                        # MailChimp Campaign relates to OroCRM MarketingList and
                        # MailChimp Campaign has "sent" status
                        conditions:
                            @and:
                                - @empty: $emailCampaign
                                - @not_empty: $staticSegment
                                - @not_empty: $staticSegment.marketingList
                                - @equal: [$status, 'sent']
                        actions:
                            - @create_entity: # Create OroCRM EmailCampaign
                                class:     OroCRM\Bundle\CampaignBundle\Entity\EmailCampaign
                                attribute: $emailCampaign
                                data:
                                    name: $title
                                    schedule: $.scheduleManual
                                    sent: true
                                    sentAt: $sendTime
                                    senderEmail: $fromEmail
                                    senderName: $fromName
                                    transport: $.mailchimpTransport
                                    owner: $channel.defaultUserOwner
                                    organization: $channel.defaultUserOwner.organization
                                    marketingLIst: $staticSegment.marketingList
                            - @create_entity: # Create MailChimpTransportSettings
                                class:     OroCRM\Bundle\MailChimpBundle\Entity\MailChimpTransportSettings
                                attribute: $emailCampaign.transportSettings
                                data:
                                    channel: $channel
#                                    template: $template

    mailchimp_handle_member_state:
        label:   Create MarketingListUnsubscribedItem for MailChimp unsubscribed Member
        enabled: true
        entity:  OroCRM\Bundle\MailChimpBundle\Entity\Member
        actions_configuration:
            - @tree:
                actions:
                    # Prepare constants values
                    - @assign_constant_value:
                        attribute: $.statusUnsubscribed
                        value: OroCRM\Bundle\MailChimpBundle\Entity\Member::STATUS_UNSUBSCRIBED
                    - @assign_constant_value:
                        attribute: $.statusCleaned
                        value: OroCRM\Bundle\MailChimpBundle\Entity\Member::STATUS_CLEANED
                    # Create OroCRM MarketingListUnsubscribedItem
                    - @create_marketing_list_unsubscribed_item:
                        conditions:
                            @or:
                                - @equal: [$status, $.statusUnsubscribed]
                                - @equal: [$status, $.statusCleaned]

    schedule_mailchimp_segment_synchronization:
        label:   Schedule MailChimp Static Segment synchronization
        enabled: true
        entity:  OroCRM\Bundle\MailChimpBundle\Entity\StaticSegment
        actions_configuration:
            - @assign_constant_value:
                attribute: $.statusUnsubched
                value: OroCRM\Bundle\MailChimpBundle\Entity\StaticSegment::STATUS_NOT_SYNCED
            - @assign_constant_value:
                attribute: $.statusScheduled
                value: OroCRM\Bundle\MailChimpBundle\Entity\StaticSegment::STATUS_SCHEDULED
            - @tree:
                conditions:
                    @or:
                        - @empty: $originId
                        - @equal: [$syncStatus, $.statusUnsubched]
                        - @equal: [$syncStatus, $.statusScheduled]
                actions:
                    - @format_string:
                        attribute: $.segmentArguments
                        string: '--segments=%segment_id%'
                        arguments:
                            segment_id: $id
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        flush: true
                        arguments:
                            - 'oro:cron:mailchimp:sync-segment'
                            - [$.segmentArguments]

triggers:
    synchronize_marketing_list_item_for_mailchimp_member_activity:
        -
            event:    create
            queued:   true

    create_email_campaign_for_mailchimp_campaign:
        -
            event:    create
            queued:   true

    mailchimp_handle_member_state:
        -
            event:    update
            field:    status

    schedule_mailchimp_segment_synchronization:
        -
            event:    create
        -
            event:    update
            field:    syncStatus
        -
            event:    update
            field:    originId
