OroCRM\Bundle\MailChimpBundle\Entity\MailChimpTransport:
    properties:
        apiKey:
            - NotBlank: ~
            - Length:
                min: 32
            - Regex:
                pattern: '/^[a-z0-9]{32,}-[a-z]{2,}[0-9]+$/'
                message: API Key is invalid

OroCRM\Bundle\MailChimpBundle\Entity\MailChimpTransportSettings:
    properties:
        channel:
            - NotBlank: ~
#        template:
#            - NotBlank: ~

Oro\Bundle\MarketingListBundle\Entity\MarketingList:
    constraints:
        - OroCRM\Bundle\MailChimpBundle\Validator\Constraints\EmailColumnConstraint: ~

OroCRM\Bundle\MailChimpBundle\Entity\StaticSegment:
    constraints:
        - OroCRM\Bundle\MailChimpBundle\Validator\Constraints\UniqueStaticSegmentNameConstraint: ~
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 100
                maxMessage: "MailChimp Segment name cannot be longer than {{ limit }} characters long"
        channel:
            - NotBlank: ~
        subscribersList:
            - NotBlank: ~
        marketingList:
            - NotBlank: ~
        syncStatus:
            - NotBlank: ~

OroCRM\Bundle\MailChimpBundle\Entity\Member:
    properties:
        email:
            - Email: ~
            - NotBlank: ~
        status:
            - NotBlank: ~

OroCRM\Bundle\MailChimpBundle\Entity\MemberActivity:
    properties:
        email:
            - Email: ~
            - NotBlank: ~
        action:
            - NotBlank: ~
        member:
            - NotBlank: ~

OroCRM\Bundle\MailChimpBundle\Entity\Campaign:
    properties:
        originId:
            - NotBlank: ~
        webId:
            - NotBlank: ~
        status:
            - NotBlank: ~

OroCRM\Bundle\MailChimpBundle\Entity\StaticSegmentMember:
    properties:
        staticSegment:
            - NotBlank: ~
        member:
            - NotBlank: ~
        state:
            - NotBlank: ~

OroCRM\Bundle\MailChimpBundle\Entity\SubscribersList:
    properties:
        originId:
            - NotBlank: ~
        webId:
            - NotBlank: ~
        name:
            - NotBlank: ~

OroCRM\Bundle\MailChimpBundle\Entity\Template:
    properties:
        originId:
            - NotBlank: ~
        type:
            - NotBlank: ~
        name:
            - NotBlank: ~

OroCRM\Bundle\MailChimpBundle\Entity\ExtendedMergeVar:
    properties:
        staticSegment:
            - NotBlank: ~
        name:
            - NotBlank: ~
            - Length:
                max: 255
        label:
            - NotBlank: ~
            - Length:
                max: 255
        tag:
            - NotBlank: ~
            - Length:
                max: 10
        state:
            - NotBlank: ~

OroCRM\Bundle\MailChimpBundle\Entity\MemberExtendedMergeVar:
    proerties:
        staticSegment:
            - NotBlank: ~
        member:
            - NotBlank: ~
        state:
            - NotBlank: ~
